import Config

database_url = System.get_env("DATABASE_URL")

db_config =
  if database_url do
    [
      url: database_url,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
    ]
  else
    [
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "hrafnsyn_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
    ]
  end

# Configure your database
config :hrafnsyn, Hrafnsyn.Repo, db_config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :hrafnsyn, HrafnsynWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VBwDbM9EYW59Sh6ECRsOQmVhrf3e1FgReRPWGcRGgBKL4lka3QnSJ/DxqGc86s3B",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:hrafnsyn, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:hrafnsyn, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :hrafnsyn, HrafnsynWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/hrafnsyn_web/router\.ex$",
      ~r"lib/hrafnsyn_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :hrafnsyn, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

config :hrafnsyn, Hrafnsyn.Collectors,
  sources: [
    %{
      id: "planes-main",
      name: "Airplane SDR",
      vehicle_type: :plane,
      adapter: :dump1090,
      base_url: System.get_env("HRAFNSYN_PLANE_URL", "http://10.255.101.202"),
      poll_interval_ms: 1_000,
      enabled: true
    },
    %{
      id: "boats-main",
      name: "Boat SDR",
      vehicle_type: :vessel,
      adapter: :ais_catcher,
      base_url: System.get_env("HRAFNSYN_BOAT_URL", "http://10.255.101.202:8100"),
      poll_interval_ms: 2_500,
      enabled: true
    }
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
